### ISSUE TITLE
Unable to install numpy with pypy

### ISSUE THREAD

**Issue by Neiizo** [pypy/pypy#5230]
Hi, I think I am having the same issue issue as #5139 and [this (from another github repo)](https://github.com/mesonbuild/meson/issues/12979), but with python 3.11.
I have a program which is already fully programmed and I want it to run faster, that is why I have tried using pypy. 

I downloaded the zip and extracted it under C:\pypy, and added this to PATH. Then, inside anaconda ( in the base environment), i've run 
```cmd
pypy -m ensurepip  
pypy -m pip install numpy  

```

And I keep getting this error

```cmd
(base) C:\Users\Neizo>pypy -m pip install numpy
Collecting numpy
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  ├ù Preparing metadata (pyproject.toml) did not run successfully.
  Ôöé exit code: 2
  Ôò░ÔöÇ> [94 lines of output]
      + C:\pypy\pypy.exe C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\meson.py setup C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\.mesonpy-tw44qe80 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\.mesonpy-tw44qe80\meson-python-native-file.ini
      Exception in thread Thread-3 (_readerthread):
      Exception in thread Thread-4 (_readerthread):
      Traceback (most recent call last):
        File "C:\pypy\Lib\threading.py", line 1045, in _bootstrap_inner
          self.run()
        File "C:\pypy\Lib\threading.py", line 982, in run
          self._target(*self._args, **self._kwargs)
        File "C:\pypy\Lib\subprocess.py", line 1612, in _readerthread
          buffer.append(fh.read())
                        ^^^^^^^^^
        File "C:\pypy\Lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 54: invalid start byte
      Traceback (most recent call last):
        File "C:\pypy\Lib\threading.py", line 1045, in _bootstrap_inner
          self.run()
        File "C:\pypy\Lib\threading.py", line 982, in run
          self._target(*self._args, **self._kwargs)
        File "C:\pypy\Lib\subprocess.py", line 1612, in _readerthread
          buffer.append(fh.read())
                        ^^^^^^^^^
        File "C:\pypy\Lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 47: invalid start byte
      Traceback (most recent call last):
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\mesonmain.py", line 194, in run
          return options.run_func(options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\msetup.py", line 358, in run
          app.generate()
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\msetup.py", line 183, in generate
          return self._generate(env, capture, vslite_ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\msetup.py", line 205, in _generate
          intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 331, in __init__
          self.parse_project()
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 134, in parse_project
          self.evaluate_codeblock(self.ast, end=1)
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 190, in evaluate_codeblock
          raise e
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 182, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 196, in evaluate_statement
          return self.function_call(cur)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 521, in function_call
          res = func(node, func_args, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 596, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1315, in func_project
          self.add_languages(proj_langs, True, MachineChoice.HOST)
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1472, in add_languages
          success = self.add_languages_for(args, required, for_machine)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1515, in add_languages_for
          comp = compilers.detect_compiler_for(self.environment, lang, for_machine, skip_sanity_check)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\compilers\detect.py", line 115, in detect_compiler_for
          comp = compiler_from_language(env, lang, for_machine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\compilers\detect.py", line 112, in compiler_from_language
          return lang_map[lang](env, for_machine) if lang in lang_map else None
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\compilers\detect.py", line 614, in detect_c_compiler
          return _detect_c_or_cpp_compiler(env, 'c', for_machine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\compilers\detect.py", line 330, in _detect_c_or_cpp_compiler
          p, out, err = Popen_safe_logged(cmd, msg='Detecting compiler via')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\vendored-meson\meson\mesonbuild\utils\universal.py", line 1530, in Popen_safe_logged
          rc, out, err = p.returncode, o.strip(), e.strip()
                                       ^^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'strip'
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc
      Build dir: C:\Users\Neizo\AppData\Local\Temp\pip-install-__pju61t\numpy_a8865b354aa74310b8bc3af35db93acc\.mesonpy-tw44qe80
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4

      ..\meson.build:1:0: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

├ù Encountered error while generating package metadata.
Ôò░ÔöÇ> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
``` 

I know I at least need python 3.10, and I think there were some reasons for using 3.11, but I can't recall why at the moment.

I have to mention I have never used PyPy before, so I may have incorectly installed it, or used it, or maybe even it won't improve the run time of my program.

Do you know how I could solve this issue ?
thanks

**Comment by mattip** [comment]
I think this should have been fixed for `numpy>=2.0`. Could you clear out the caches (`pip cache info` to see what is cached, `pip cache purge` to clear it) and try again?

**Comment by Neiizo** [comment]
Hi,
Thanks for the reply !

So I did just that, and it didn't seem to solve anything

```cmd
 (base) C:\Users\Neizo>pip cache purge
Files removed: 2106

(base) C:\Users\Neizo>pypy -m ensurepip
Looking in links: c:\Users\Neizo\AppData\Local\Temp\tmp2rtg18lu
Requirement already satisfied: setuptools in c:\pypy\lib\site-packages (65.5.0)
Requirement already satisfied: pip in c:\pypy\lib\site-packages (25.0.1)

(base) C:\Users\Neizo>pypy -m pip install numpy
Collecting numpy
  Downloading numpy-2.2.3.tar.gz (20.3 MB)
     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     Ôò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║ÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò©ÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║ÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔò║Ô     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔ     ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöü 20.3/20.3 MB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  ├ù Preparing metadata (pyproject.toml) did not run successfully.
  Ôöé exit code: 2
  Ôò░ÔöÇ> [91 lines of output]
      + C:\pypy\pypy.exe C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\meson.py setup C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5 C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\.mesonpy-lxdlfes3 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\.mesonpy-lxdlfes3\meson-python-native-file.ini
      Exception in thread Thread-4 (_readerthread):
      Exception in thread Thread-3 (_readerthread):
      Traceback (most recent call last):
        File "C:\pypy\Lib\threading.py", line 1045, in _bootstrap_inner
          self.run()
        File "C:\pypy\Lib\threading.py", line 982, in run
          self._target(*self._args, **self._kwargs)
        File "C:\pypy\Lib\subprocess.py", line 1612, in _readerthread
          buffer.append(fh.read())
                        ^^^^^^^^^
        File "C:\pypy\Lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 54: invalid start byte
      Traceback (most recent call last):
        File "C:\pypy\Lib\threading.py", line 1045, in _bootstrap_inner
          self.run()
        File "C:\pypy\Lib\threading.py", line 982, in run
          self._target(*self._args, **self._kwargs)
        File "C:\pypy\Lib\subprocess.py", line 1612, in _readerthread
          buffer.append(fh.read())
                        ^^^^^^^^^
        File "C:\pypy\Lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 47: invalid start byte
      Traceback (most recent call last):
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\mesonmain.py", line 191, in run
          return options.run_func(options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\msetup.py", line 364, in run
          app.generate()
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\msetup.py", line 187, in generate
          return self._generate(env, capture, vslite_ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\msetup.py", line 209, in _generate
          intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 321, in __init__
          self.parse_project()
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 129, in parse_project
          self.evaluate_codeblock(self.ast, end=1)
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 195, in evaluate_codeblock
          raise e
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 187, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 201, in evaluate_statement
          return self.function_call(cur)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 528, in function_call
          res = func(node, func_args, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 250, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 569, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1311, in func_project
          self.add_languages(proj_langs, True, MachineChoice.HOST)
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1479, in add_languages
          success = self.add_languages_for(args, required, for_machine)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1522, in add_languages_for
          comp = compilers.detect_compiler_for(self.environment, lang, for_machine, skip_sanity_check, self.subproject)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\compilers\detect.py", line 103, in detect_compiler_for
          comp = compiler_from_language(env, lang, for_machine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\compilers\detect.py", line 100, in compiler_from_language
          return lang_map[lang](env, for_machine) if lang in lang_map else None
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\compilers\detect.py", line 611, in detect_c_compiler
          return _detect_c_or_cpp_compiler(env, 'c', for_machine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\vendored-meson\meson\mesonbuild\compilers\detect.py", line 330, in _detect_c_or_cpp_compiler
          full_version = out.split('\n', 1)[0]
                         ^^^^^^^^^^^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'split'
      The Meson build system
      Version: 1.5.2
      Source dir: C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5
      Build dir: C:\Users\Neizo\AppData\Local\Temp\pip-install-jqld1_3d\numpy_5c804eb6af5b46ea9535a2d782049da5\.mesonpy-lxdlfes3
      Build type: native build
      Project name: NumPy
      Project version: 2.2.3

      ..\meson.build:1:0: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

├ù Encountered error while generating package metadata.
Ôò░ÔöÇ> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```


I have also run `pip cache info` before doing this, and it saved 2 files. Do you need them ?

**Comment by mattip** [comment]
This probably comes from trying to detect your Visual Studio installation. Could you `set PYPY_ENABLE_WINCONSOLEIO=1` so the console output can work?

**Comment by mattip** [comment]
> I have a program which is already fully programmed and I want it to run faster, that is why I have tried using pypy.

If your program leans heavily on NumPy, you probably will not see any speed improvement. Typically PyPy + NumPy runs slower than CPython + NumPy. You should benchmark your working setup to see if the problem is in python code or in numpy code.

**Comment by Neiizo** [comment]
> > I have a program which is already fully programmed and I want it to run faster, that is why I have tried using pypy.
> 
> If your program leans heavily on NumPy, you probably will not see any speed improvement. Typically PyPy + NumPy runs slower than CPython + NumPy. You should benchmark your working setup to see if the problem is in python code or in numpy code.

Thanks for this clarification.

I use a lot of numpy arrays, but i don't think there are that many numpy operations, if that makes any difference.
I have a tried CPython, but this is also something I am not familiar with. I didn't see any run time improvement, but at the same time, I don't know if I used it correctly.

I guess I will give up  using PyPy to improve my run time. I'll keep posting in this thread, so we can solve this issue for future users.




> This probably comes from trying to detect your Visual Studio installation. Could you `set PYPY_ENABLE_WINCONSOLEIO=1` so the console output can work?

```cmd
(base) C:\Users\Neizo>set PYPY_ENABLE_WINCONSOLEIO=1

(base) C:\Users\Neizo>pypy -m pip install numpy
Collecting numpy
  Using cached numpy-2.2.3.tar.gz (20.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 2
  ╰─> [91 lines of output]
      + C:\pypy\pypy.exe C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\meson.py setup C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081 C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\.mesonpy-c96wah5f -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\.mesonpy-c96wah5f\meson-python-native-file.ini
      Exception in thread Thread-3 (_readerthread):
      Exception in thread Thread-4 (_readerthread):
      Traceback (most recent call last):
        File "C:\pypy\Lib\threading.py", line 1045, in _bootstrap_inner
          self.run()
        File "C:\pypy\Lib\threading.py", line 982, in run
          self._target(*self._args, **self._kwargs)
        File "C:\pypy\Lib\subprocess.py", line 1612, in _readerthread
          buffer.append(fh.read())
                        ^^^^^^^^^
        File "C:\pypy\Lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 54: invalid start byte
      Traceback (most recent call last):
        File "C:\pypy\Lib\threading.py", line 1045, in _bootstrap_inner
          self.run()
        File "C:\pypy\Lib\threading.py", line 982, in run
          self._target(*self._args, **self._kwargs)
        File "C:\pypy\Lib\subprocess.py", line 1612, in _readerthread
          buffer.append(fh.read())
                        ^^^^^^^^^
        File "C:\pypy\Lib\codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 47: invalid start byte
      Traceback (most recent call last):
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\mesonmain.py", line 191, in run
          return options.run_func(options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\msetup.py", line 364, in run
          app.generate()
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\msetup.py", line 187, in generate
          return self._generate(env, capture, vslite_ctx)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\msetup.py", line 209, in _generate
          intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 321, in __init__
          self.parse_project()
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 129, in parse_project
          self.evaluate_codeblock(self.ast, end=1)
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 195, in evaluate_codeblock
          raise e
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 187, in evaluate_codeblock
          self.evaluate_statement(cur)
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 201, in evaluate_statement
          return self.function_call(cur)
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreterbase\interpreterbase.py", line 528, in function_call
          res = func(node, func_args, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 250, in wrapper
          return f(*nargs, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreterbase\decorators.py", line 569, in wrapper
          return f(*wrapped_args, **wrapped_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1311, in func_project
          self.add_languages(proj_langs, True, MachineChoice.HOST)
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1479, in add_languages
          success = self.add_languages_for(args, required, for_machine)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\interpreter\interpreter.py", line 1522, in add_languages_for
          comp = compilers.detect_compiler_for(self.environment, lang, for_machine, skip_sanity_check, self.subproject)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\compilers\detect.py", line 103, in detect_compiler_for
          comp = compiler_from_language(env, lang, for_machine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\compilers\detect.py", line 100, in compiler_from_language
          return lang_map[lang](env, for_machine) if lang in lang_map else None
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\compilers\detect.py", line 611, in detect_c_compiler
          return _detect_c_or_cpp_compiler(env, 'c', for_machine)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\vendored-meson\meson\mesonbuild\compilers\detect.py", line 330, in _detect_c_or_cpp_compiler
          full_version = out.split('\n', 1)[0]
                         ^^^^^^^^^^^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'split'
      The Meson build system
      Version: 1.5.2
      Source dir: C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081
      Build dir: C:\Users\Neizo\AppData\Local\Temp\pip-install-h8aue5tf\numpy_4b3216c5fe0248788c300eb9f0a6a081\.mesonpy-c96wah5f
      Build type: native build
      Project name: NumPy
      Project version: 2.2.3

      ..\meson.build:1:0: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Maybe I should highlight that I'm doing this in an Anaconda command terminal, so I'm not really sure if the IDE actually matters. 

I also realize I didn't mention this. I've tried creating a new environment, using this [guide ](https://pypy.org/posts/2022/11/pypy-and-conda-forge.html), but I also can't. 

```cmd
(base) C:\Users\Neizo>conda create -c conda-forge -n testpypy pypy python=3.10
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.10
pypy -> python[version='3.6.12|3.6.12|3.7.10|3.7.10|3.7.12|3.8.12|3.8.13|3.8.16|3.9.16|3.9.17|3.9.18|3.9.12|3.9.10|3.7.9|3.6.9|3.6.9|3.6.9|3.6.9',build='2_73_pypy|4_73_pypy|0_73_pypy|0_73_pypy|0_73_pypy|0_73_pypy|0_73_pypy|0_73_pypy|0_73_pypy|0_73_pypy|0_73_pypy|1_73_pypy|0_73_pypy|1_73_pypy|5_73_pypy|5_73_pypy|3_73_pypy|1_73_pypy|0_73_pypy']
```
Apparently, with conda forge, python 3.10 isn't supported yet

Finally, I have tried creating a new environement, instead of working in `base`, and I still get the same error.

**Comment by mattip** [comment]
Could you try at a regular DOS prompt, not inside anaconda? Conda-forge is not supporting PyPy any more, so there is no reason to try PyPy inside a conda/andaconda/conda-forge environment.

**Comment by mattip** [comment]
Do you have a compiler installed?

**Comment by Neiizo** [comment]
Hi,
Sorry, i missed your last reply.

I'm not sure I understand what you mean by that, because I don't think there are python compiler, only interpreter. I have created my python environment using anaconda, and run everything off of anaconda's terminal and in VSCode.
Do you mean maybe a C Compiler ?

**Comment by mattip** [comment]
> Do you mean maybe a C Compiler ?

**Comment by mhechthz** [comment]
Have the same issue:

```
C:\Users\...\pip-install-yxd5_itd\numpy_296bd989ea1b4970b8f7a88ad6ea5d42\vendored-meson\meson\mesonbuild\compilers\detect.py", line 330, in _detect_c_or_cpp_compiler
          full_version = out.split('\n', 1)[0]
                         ^^^^^^^^^^^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'split'
      The Meson build system
      Version: 1.5.2
      Source dir: C:\Users\...\pip-install-yxd5_itd\numpy_296bd989ea1b4970b8f7a88ad6ea5d42
      Build dir: C:\Users\...\pip-install-yxd5_itd\numpy_296bd989ea1b4970b8f7a88ad6ea5d42\.mesonpy-c0wbx19j
      Build type: native build
      Project name: NumPy
      Project version: 2.2.4

      ..\meson.build:1:0: ERROR: Unhandled python exception

          This is a Meson bug and should be reported!
```

and have no Visual Studio C/C++ compiler istalled, since with CPython I never needed one. Will PyPy only work with this compiler?

**Comment by mattip** [comment]
You either need a compiler or must use pre-compiled packages (wheels) for things like NumPy that wrap uncompiled C/C++ code. Same for rust or go code: you either need a compiler or need someone else to compile for you. When you `pip install`, you can either download a compiled package or source code. If you want to use NumPy with PyPy, you can use the precompiled wheels from [conda-forge](https://anaconda.org/scientific-python-nightly-wheels/numpy) for PyPy 3.11, but I fear you will find you need some other package (scipy? matplotlib?) that does not even attempt to build wheels for PyPy. Note if your goal is to speed up code that uses NumPy heavily, you will be dissapointed, especially on windows. PyPy + Numpy is quite a bit slower than CPython + Numpy, since
- the JIT cannot look into C compiled code, which is the heart of NumPy
- CPython, written in C, interfaces more seamlessly (quickly) with C code than PyPy does
